### ISSUE TITLE
Roadmap to 0.1.2 (WIP)

### ISSUE THREAD

**Issue by edwin0cheng** [edwin0cheng/unigame#43]
#### Standard Material
- [ ] Decide how the standard material and render pipelines works
- [ ] Sky Light 

#### Engine Refactoring
- [ ] Change Component from Rc<RefCell<T>> to Rc<T:Clone> which allow us to use Rc::make_mut instead of borrow_mut()
- [ ] Add TextRenderer for support bitmap and truetype font (maybe by RustType?)
- [ ] Able to us resizable / fixed window 
- [ ] Able to toggle fullscreen 

#### File Structures
- [ ] Use workspace instead of virtual crate
- [ ] Find a way to allow end-user to use the engine with standard assets

#### Assets
- [ ] gltf support

#### Unrust-Editor Basic
... TBD

**Comment by jice-nospam** [comment]
Won't using Rc::make_mut lead to a lot of clone() operations ? Is borrow_mut slow ?

**Comment by edwin0cheng** [comment]
No, but borrow_mut() will panic :
```
let a = com.borrow_mut();
let b = com.borrow_mut();   // this one will panic
```
For examples, if 2 actors are cross referenced, it maybe panic and it is quite hard to debug.

On the other hand, Rc::make_mut only clone it when its reference count > 1. And this behavior should be more reasonble for some kind of resources. For example, material should be cloned when its material parameter was changed.

**Comment by edwin0cheng** [comment]
> SDL2 would also allow gamepad support on native part
Yes, but i just found that [sdl2 crate](https://github.com/Rust-SDL2/rust-sdl2) are quite complicated to build. It need the end user of our crate to build sdl2 library by them, Do we have other options here?

**Comment by jice-nospam** [comment]
gfx-rs is the official rust API for that and should be wasm compatible in the long term, but I find it a bit overengineered and I've no idea if it can replace what we have in its current state. It seems still very unstable.

**Comment by edwin0cheng** [comment]
>  I find it a bit overengineered
Yes indeed, would it possible we fix it in the upstream winit for the window features ?

And for the gamepad one, i just did some research, basically we have some options (except sdl2):
* gilrs https://github.com/Arvamer/gilrs
* reminisce https://github.com/TomBebbington/reminisce

And only gilrs is decent one, but it do not support MacOS ...

**Comment by jice-nospam** [comment]
I already tried to bring fullscreen support to winit (for windows only) but it's not that easy...  I probably didn't spend enough time on it but I didn't manage to make it work. And this would require the same amount of work for MacOs and Linux. Not something I'm looking for to spend my time on. 

As for joystick support, reminisce uses sdl2 and gilrs is using the winapi. Not something I would trust for windows video games where directX seems a much better solution.

Maybe we should rather settle with our current engine and wait for the rust gamedev ecosystem to be more mature... We should focus on web target first and upgrade native platform when we find an suitable crate.

**Comment by edwin0cheng** [comment]
> Maybe we should rather settle with our current engine and wait for the rust gamedev ecosystem to be more mature... We should focus on web target first and upgrade native platform when we find an suitable crate.

Yes indeed, i will keep an eye on it. but for the native joystick support, i will try to implement using sdl2 as temp solution as i don't want to break the symmetric.

**Comment by edwin0cheng** [comment]
For the record, i am trying to implment back missing features of winit : 
1. display features for Windows (https://github.com/tomaka/winit/pull/457)
2. display features for Mac (Waiting for the previous one merged)

**Comment by jice-nospam** [comment]
awesome !

**Comment by edwin0cheng** [comment]
Finally we can implement fullscreen and no decoration windows in unrust now :)

**Comment by jice-nospam** [comment]
Hey,that's great! I'm back from one week vacation. I'll check this (and the new headless mode) asap.

**Comment by viperconsole** [comment]
We should definitely fork it, but maybe not re-brand it. Just add it as a dependency to uni-pad. The commits are only a few weeks old, it's probably not abandoned yet. Maybe I can integrate it with uni-pad to check existing linux/windows support while you work on the mac port.

**Comment by jice-nospam** [comment]
We should definitely fork it, but maybe not re-brand it. Just add it as a dependency to uni-pad. The commits are only a few weeks old, it's probably not abandoned yet. Maybe I can integrate it with uni-pad to check existing linux/windows support while you work on the mac port.

**Comment by edwin0cheng** [comment]
Thanks, I would start to works on MacOS part in this week.
